"""first

Revision ID: 8405c4716dbf
Revises: 
Create Date: 2025-11-20 12:37:34.998079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8405c4716dbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('qr_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('Valid', 'Invalid', 'Expired', 'Duplicate', name='status_enum'), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.visitor_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_logs_qr_code'), 'logs', ['qr_code'], unique=False)
    op.drop_index(op.f('idx_visitors_qr'), table_name='visitors')
    op.create_unique_constraint('idx_visitors_qr', 'visitors', ['qr_code'])
    op.create_index(op.f('ix_visitors_email'), 'visitors', ['email'], unique=False)
    op.create_index(op.f('ix_visitors_visitor_id'), 'visitors', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_visitor_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_email'), table_name='visitors')
    op.drop_constraint('idx_visitors_qr', 'visitors', type_='unique')
    op.create_index(op.f('idx_visitors_qr'), 'visitors', ['qr_code'], unique=False)
    op.drop_index(op.f('ix_logs_qr_code'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
